/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GalleryPutRequest {
    #[serde(rename = "locale", deserialize_with = "Option::deserialize")]
    pub locale: Option<models::SupportedLocale>,
    /// Comment on this item
    #[serde(rename = "tweet", deserialize_with = "Option::deserialize")]
    pub tweet: Option<String>,
    /// Image identifier
    #[serde(rename = "imageId")]
    pub image_id: i32,
}

impl GalleryPutRequest {
    pub fn new(locale: Option<models::SupportedLocale>, tweet: Option<String>, image_id: i32) -> GalleryPutRequest {
        GalleryPutRequest {
            locale,
            tweet,
            image_id,
        }
    }
}

