/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GalleryIdPatchRequest {
    #[serde(rename = "locale", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub locale: Option<Option<models::SupportedLocale>>,
    #[serde(rename = "tweet", skip_serializing_if = "Option::is_none")]
    pub tweet: Option<String>,
    #[serde(rename = "imageId", skip_serializing_if = "Option::is_none")]
    pub image_id: Option<i32>,
    #[serde(rename = "trashed", skip_serializing_if = "Option::is_none")]
    pub trashed: Option<bool>,
}

impl GalleryIdPatchRequest {
    pub fn new() -> GalleryIdPatchRequest {
        GalleryIdPatchRequest {
            locale: None,
            tweet: None,
            image_id: None,
            trashed: None,
        }
    }
}

