/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagePost201Response {
    /// Image identifier in plain text
    #[serde(rename = "id")]
    pub id: i32,
    /// Publicly accessible image URL
    #[serde(rename = "url")]
    pub url: String,
}

impl ImagePost201Response {
    pub fn new(id: i32, url: String) -> ImagePost201Response {
        ImagePost201Response {
            id,
            url,
        }
    }
}

