/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagePutRequest {
    /// CDN URL, publicly accessible
    #[serde(rename = "url")]
    pub url: String,
    /// Alernative text describing the image
    #[serde(rename = "alt")]
    pub alt: String,
}

impl ImagePutRequest {
    pub fn new(url: String, alt: String) -> ImagePutRequest {
        ImagePutRequest {
            url,
            alt,
        }
    }
}

