/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StringsByLocaleGet200Response {
    #[serde(rename = "en")]
    pub en: Vec<String>,
    #[serde(rename = "zh")]
    pub zh: Vec<String>,
    #[serde(rename = "zh-tw")]
    pub zh_tw: Vec<String>,
}

impl StringsByLocaleGet200Response {
    pub fn new(en: Vec<String>, zh: Vec<String>, zh_tw: Vec<String>) -> StringsByLocaleGet200Response {
        StringsByLocaleGet200Response {
            en,
            zh,
            zh_tw,
        }
    }
}

