/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateIdPatchRequest {
    /// Target locale of this post
    #[serde(rename = "locale", skip_serializing_if = "Option::is_none")]
    pub locale: Option<models::SupportedLocale>,
    /// Top header of the card
    #[serde(rename = "header", skip_serializing_if = "Option::is_none")]
    pub header: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
    pub summary: Option<String>,
    /// Image identifier
    #[serde(rename = "cover", skip_serializing_if = "Option::is_none")]
    pub cover: Option<i32>,
    #[serde(rename = "mask", skip_serializing_if = "Option::is_none")]
    pub mask: Option<models::Shape>,
    #[serde(rename = "trashed", skip_serializing_if = "Option::is_none")]
    pub trashed: Option<bool>,
}

impl UpdateIdPatchRequest {
    pub fn new() -> UpdateIdPatchRequest {
        UpdateIdPatchRequest {
            locale: None,
            header: None,
            title: None,
            summary: None,
            cover: None,
            mask: None,
            trashed: None,
        }
    }
}

