/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePutRequest {
    /// Target locale of this post
    #[serde(rename = "locale")]
    pub locale: models::SupportedLocale,
    /// Top header of the card, in bold color and monospaced font
    #[serde(rename = "header")]
    pub header: String,
    /// Title in Futura font
    #[serde(rename = "title")]
    pub title: String,
    /// Tweet in Sans font
    #[serde(rename = "summary")]
    pub summary: String,
    /// Cover image identifier
    #[serde(rename = "cover", skip_serializing_if = "Option::is_none")]
    pub cover: Option<i32>,
    /// Mask to the cover image
    #[serde(rename = "mask")]
    pub mask: models::Shape,
}

impl UpdatePutRequest {
    pub fn new(locale: models::SupportedLocale, header: String, title: String, summary: String, mask: models::Shape) -> UpdatePutRequest {
        UpdatePutRequest {
            locale,
            header,
            title,
            summary,
            cover: None,
            mask,
        }
    }
}

