/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GalleryItem {
    /// Gallery item Identifier
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "locale", deserialize_with = "Option::deserialize")]
    pub locale: Option<models::SupportedLocale>,
    /// Comment on this item
    #[serde(rename = "tweet", deserialize_with = "Option::deserialize")]
    pub tweet: Option<String>,
    /// Image identifier
    #[serde(rename = "image")]
    pub image: String,
    /// Item creation time in ISO format
    #[serde(rename = "created")]
    pub created: String,
    /// Alternative text describing image
    #[serde(rename = "alt")]
    pub alt: String,
    /// Whether to not display this item in the gallery
    #[serde(rename = "trashed")]
    pub trashed: bool,
}

impl GalleryItem {
    pub fn new(id: i32, locale: Option<models::SupportedLocale>, tweet: Option<String>, image: String, created: String, alt: String, trashed: bool) -> GalleryItem {
        GalleryItem {
            id,
            locale,
            tweet,
            image,
            created,
            alt,
            trashed,
        }
    }
}

