/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Image {
    /// Image identifier
    #[serde(rename = "id")]
    pub id: i32,
    /// Publicly accessible URL
    #[serde(rename = "url")]
    pub url: String,
    /// Alernative text describing the image content
    #[serde(rename = "alt")]
    pub alt: String,
}

impl Image {
    pub fn new(id: i32, url: String, alt: String) -> Image {
        Image {
            id,
            url,
            alt,
        }
    }
}

