/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Shape {
    #[serde(rename = "clover")]
    Clover,
    #[serde(rename = "elevenSidedStar")]
    ElevenSidedStar,
    #[serde(rename = "sixSidedStar")]
    SixSidedStar,
    #[serde(rename = "tiltedOval")]
    TiltedOval,
    #[serde(rename = "tiltedPentagon")]
    TiltedPentagon,
    #[serde(rename = "tiltedRectangle")]
    TiltedRectangle,

}

impl std::fmt::Display for Shape {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Clover => write!(f, "clover"),
            Self::ElevenSidedStar => write!(f, "elevenSidedStar"),
            Self::SixSidedStar => write!(f, "sixSidedStar"),
            Self::TiltedOval => write!(f, "tiltedOval"),
            Self::TiltedPentagon => write!(f, "tiltedPentagon"),
            Self::TiltedRectangle => write!(f, "tiltedRectangle"),
        }
    }
}

impl Default for Shape {
    fn default() -> Shape {
        Self::Clover
    }
}

