/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupportedLocale {
    #[serde(rename = "en")]
    En,
    #[serde(rename = "zh")]
    Zh,
    #[serde(rename = "zh-tw")]
    ZhTw,

}

impl std::fmt::Display for SupportedLocale {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::En => write!(f, "en"),
            Self::Zh => write!(f, "zh"),
            Self::ZhTw => write!(f, "zh-tw"),
        }
    }
}

impl Default for SupportedLocale {
    fn default() -> SupportedLocale {
        Self::En
    }
}

