/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePostCover {
    /// Image URL
    #[serde(rename = "image")]
    pub image: String,
    /// Alternative text
    #[serde(rename = "alt")]
    pub alt: String,
    /// Image identifier
    #[serde(rename = "id")]
    pub id: i32,
}

impl UpdatePostCover {
    pub fn new(image: String, alt: String, id: i32) -> UpdatePostCover {
        UpdatePostCover {
            image,
            alt,
            id,
        }
    }
}

