/*
 * api
 *
 * API to post and manage stuff
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePost {
    /// Reference ID
    #[serde(rename = "id")]
    pub id: i32,
    /// ISO format time representation
    #[serde(rename = "created")]
    pub created: String,
    /// Leading header text, in bold color and monospace font
    #[serde(rename = "header")]
    pub header: String,
    /// Title text in Futura font
    #[serde(rename = "title")]
    pub title: String,
    /// Tweet content in system Sans font
    #[serde(rename = "summary")]
    pub summary: String,
    /// Shape of the mask
    #[serde(rename = "mask")]
    pub mask: models::Shape,
    /// Target locale of the post
    #[serde(rename = "locale")]
    pub locale: models::SupportedLocale,
    /// Whether to not display this post
    #[serde(rename = "trashed")]
    pub trashed: bool,
    #[serde(rename = "cover", deserialize_with = "Option::deserialize")]
    pub cover: Option<Box<models::UpdatePostCover>>,
}

impl UpdatePost {
    pub fn new(id: i32, created: String, header: String, title: String, summary: String, mask: models::Shape, locale: models::SupportedLocale, trashed: bool, cover: Option<models::UpdatePostCover>) -> UpdatePost {
        UpdatePost {
            id,
            created,
            header,
            title,
            summary,
            mask,
            locale,
            trashed,
            cover: if let Some(x) = cover {Some(Box::new(x))} else {None},
        }
    }
}

